### PR TITLE
Updates to Help I Need Heat

### PR DESCRIPTION
**Pull request by hwinn4**
Hey Chris, 

Happy New Year! I worked on a few of the issues for this repo and did the following: 
1. Adds code to handle case where the outdoor temperature is too warm for regulations to take effect. 
2. Adds code to handle months outside of "heat season"
3. Adds language to "step 1" to direct users to the online 311 form and NYCHA residents to the Customer Contact Center

I look forward to your feedback and am happy to make adjustments to the code based on your feedback. 

Thanks!

-Hilary

### CODE REVIEW

**Comment by clhenrick** [comment]
Terrific! Thanks so much Hillary, I will take a look at this tonight or the next couple days. Appreciate your help!

**Comment by clhenrick** [comment]
@hwinn4  I looked over the code and it's pretty darn good! Only two things I would like to see changed are:
1. On the 311 complaint slide: increase the `<p>`'s width to 90-100%, left-align them, and reduce their vertical spacing as the increased amount of text pushes down the buttons on smaller laptop screen sizes.
2. Use the [`.hidden` helper class](http://www.w3schools.com/bootstrap/bootstrap_ref_css_helpers.asp) in Bootstrap to hide / show what message is displayed on the landing page. This will make the logic a little more dry for this part as well.

Let me know if this makes sense, and again thanks very much for your contribution.

**Comment by hwinn4** [comment]
Hi Chris,

Thanks for your feedback! I will go ahead and work on implementing the
changes you suggested. I will let you know if I have any questions.

Best,

Hilary Winn

**Comment by hwinn4** [comment]
Hey Chris, 

I adjusted the 311 complaints slide by adding new CSS rules for the <p> tags on that slide. What's the best way to test how the app will look on different devices?

Also, I added the .hidden class to the 3 divs for the landing page. I am not sure if I understood your suggestion about how to use the class in conjunction with jQuery. I added a command like this one to each part of the conditional:

$isNotHeatSeason.removeClass('hidden');

Let me know if I should adjust my work or approach. Thanks!

**Comment by clhenrick** [comment]
Great, the 311 slide looks good!

As for toggling the the landing message you're on the right track: For each conditional statement you'll not only want to remove the `.hidden` class from the message to be shown but you'll also want to add it to the messages that won't be shown. You can do `$selector.addClass('.hidden');` and jQuery will add the `.hidden` class if it's not already an attribute of the selector's DOM node.

I realized right now that the conditional to display the message only happens once upon the app loading. We may want to have a [setInterval](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setInterval) function on `displayTemperatureInfo()` so that if there's an edge case where someone has the app open on their browser, checks it in the morning where insideTemp is true, then checks it again later in the day and due to the temperature insideTemp should be false. This would also be a good way to have the current time and temperature update on the app's landing page, say once a minute.

Could we also add 'AM' / 'PM' to the current time?

**Comment by clhenrick** [comment]
As far as looking at how the app displays in other devices there are a few options:
1. Use Chrome's dev-tools to mimic other devices such as phones, tablets, etc.
2. Use the iOS simulator in XCode then go to localhost in Safari of the simulator
3. Push a `gh-pages` branch to your own forked repo then visit the URL `http://hwinn4.github.io/help-i-need-heat/app/` on various devices.

The responsive CSS layout should probably be another issue in of itself so I wouldn't worry too much about it for this pull request. I just happened to run into a similar problem with overflowing slide text before and remembered it being a somewhat quick fix.

**Pull request merged**
